apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: r-experiment
spec:
  environments:
    - name: dev
      build:
        from: master
  components:
    - name: r-experiment
      src: .
      publicPort: http
      ports:
       - name: http
         port: 80