apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: python-flask
spec:
  environments:
    - name: dev
      build:
        from: master
  components:
    - name: python-flask
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 80